### ISSUE TITLE
shuf(1) ignores what is after the nul character in input file (except with -z)

### ISSUE THREAD

**Issue by zeda-para-iba** [ibara/shuf#1]
If the input file contains a nul character, and I am not using the flag `-z`, the nul character and everything after it until a new line is ignored.

For example, in the image, I have a file named test with the following content:

    xa
    y\000a
    za

Where the `\000` is a nul character (as you can see in the output of `vis(1)`, a program that makes control characters like nul visible).

When I shuf it with `./shuf test`, the character `a` and the nul character before it disappears.

![tmp](https://user-images.githubusercontent.com/63294608/80926180-16beef00-8d85-11ea-8bb5-cc14c9824128.png)

The code transforms newlines into nul characters and use `printf(3)` to print from the beginning of the line until the newline made into a nul character.  The problem is that, when I have a nul character in the input file, `shuf(1)` thinks it was originally a newline made into nul character, and print from the beginning of the line until it.

**Comment by ibara** [comment]
Hello --

You're right! This was an oversight on my part.
I believe I have a fix for the issue which I will commit in the morning.

**Comment by zeda-para-iba** [comment]
I tried a solution [here](https://codereview.stackexchange.com/questions/241688/implementation-of-gnu-shuf1-now-supporting-nul-characters).

Instead of transforming newlines into nuls, it creates two arrays pointing to the buffer: one containing pointers to the beginning of each line, and the other containing pointers to the end of each line. Then it shufs both arrays parallelly, and loops printing from the beginning of each line to its end using `write(2)`.  
Unfortunately, it uses twice as memory as the previous version.

It is not an elegant solution since I am still new to C.  
This is my first issue after having read a code.

We both had the same idea on implementing `shuf(1)`.  
I [implemented `shuf(1)` once](https://codereview.stackexchange.com/questions/240706/posix-bsd-extensions-implementation-of-shuf1/240712) by transforming newlines into nuls and got the same issue.

**Comment by ibara** [comment]
Behavior-wise, this should now be fixed. Please double check.
There are some obvious wins to be made in terms of performance, which you are welcome to implement.

**Comment by zeda-para-iba** [comment]
I think that looping at each line to find the size of the line is very time-consuming and add more complexity to the algorithm.

A solution would be creating an array of line-sizes.  
But it has the downside of sacrificing memory for saving cpu time...   
The question is which one to save: memory or cpu.

**Comment by ibara** [comment]
> There are some obvious wins to be made in terms of performance, which you are welcome to implement.
